name: Release

on:
  push:
    tags:
      - 'v*' # Сработает, когда ты создашь тег, например v1.0.0

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: calculator-free-math-linux
            asset_name: calculator-free-math-linux
          - os: windows-latest
            artifact_name: calculator-free-math.exe
            asset_name: calculator-free-math-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwayland-dev libxkbcommon-dev

      - name: Build
        run: cargo build --release

      - name: Rename and Prepare (Windows)
        if: matrix.os == 'windows-latest'
        run: mv target/release/calculator_pro.exe ${{ matrix.asset_name }}

      - name: Rename and Prepare (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/calculator_pro ${{ matrix.asset_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}